### ISSUE TITLE
Update readme instructions for debug

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#131]
Now that the code is split into multiple files, we need to adjust the user debug instructions to account for that (instead of just downloading TotalConnectClient.py and info.py).

**Comment by dulitz** [comment]
Also, the live tests and other CLI executables should probably not live inside the package directory `total_connect_client`. They can't use relative imports (e.g. `import .client`) because `__main__` modules are not part of any package. They can't use `import client` because pip didn't set up PYTHONPATH that way.

If the executables live outside the package directory (like total-connect-client/debugging) then they can do `from total_connect_client import TotalConnectClient` just like any other application.

**Comment by austinmroczek** [comment]
one reason to leave them in the package directory would be to just tell users that need debug to do:
`python -m total_connect_client.info username password`
instead of trying to get them to download new files (which in the past led to lots of hand holding on how to use `wget` etc)

**Comment by dulitz** [comment]
That sounds like a very good reason. We'll have to make sure it really works outside the build/test environment.
