### ISSUE TITLE
Unknown ZoneStatus is not caught properly

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#171]
Reminder to look at how an unknown ZoneStatus is not caught in zone._update.  

Tried writing a test for it but couldn't force a ValueError even though an unknown status is provided.  Ran out of time to fix.

**Comment by dulitz** [comment]
ZoneStatus is an IntFlag since it's a bitfield. They're made to be
composed, so the value wouldn't be expected (much less required) to be
present in the enum. I think the typical way to add checking would be to
define MAXVALUE as 511, and then when you create it raise if the value is >
MAXVALUE.

Usually for bitfields you want to be able to support the addition of more
bits and I think that's true here too. You could log a warning if it's
greater than MAX_KNOWN_VALUE and then proceed.

**Comment by TheGreatPJDJ** [comment]
+1 to getting this fix merged ASAP. It's blowing up the integration currently and forcing a reconfiguration every time the error is thrown.

**Comment by austinmroczek** [comment]
@TheGreatPJDJ please post your log messages for me.  I don't think this is quite the same issue, and I want to make sure we have you covered

**Comment by TheGreatPJDJ** [comment]
@austinmroczek see the error I'm noting in my logs:

`2021-12-09 14:54:54 ERROR (SyncWorker_1) [total_connect_client.zone] unknown ZoneType 22 in OrderedDict([('PartitionId', 1), ('Batterylevel', -1), ('Signalstrength', -1), ('zoneAdditionalInfo', None), ('ZoneID', 18), ('ZoneStatus', 0), ('ZoneTypeId', 22), ('CanBeBypassed', 0), ('ZoneFlags', None)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues`

**Comment by TheGreatPJDJ** [comment]
I see this is an unknown ZoneType and not ZoneStatus. Is it a similar problem? Does throwing an error cause the integration to need to be reconfigured? Happens every couple of days.

**Comment by austinmroczek** [comment]
Unknown ZoneType was fixed in https://github.com/craigjmidwinter/total-connect-client/issues/167 and others.  It should be fixed via https://github.com/home-assistant/core/pull/59695 in Home Assistant 2021.12.x

That's separate from this issue, which is a problem where we never log or notify the user if an unknown ZoneStatus appears.

**Comment by TheGreatPJDJ** [comment]
My mistake. Thank you for the information.
