### ISSUE TITLE
Potential issue with authentication error

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#180]
This is mostly note-to-self, but welcome feedback from others

Look at https://github.com/home-assistant/core/issues/66537 where users are being told to re-authenticate TotalConnect.  It's [line 83](https://github.com/home-assistant/core/blob/a131b78a704d568509937600bf5cf872086d7dbc/homeassistant/components/totalconnect/__init__.py#L83) where an AuthenticationError exception from total_connect_client triggers "re-authentication" inside Home Assistant.  However, the username and password are then re-entered and the system works.

I suspect the sporadic -100 authentication error that we sometimes get.  It's never quite clear what it means, but it seems to be some sort of error where the authentication process cannot complete, but NOT an indicator that the username/password is bad.

We used to handle it as an error that resulted in retrying the request, like shown in https://github.com/craigjmidwinter/total-connect-client/commit/d3854abf4d6f15f02bbe08d1688192048533437d

Now it throws an AuthenticationError (along with a truly bad username/password and a bad usercode).  I think we need to make it one of the RetryableTotalConnectError instead.

**Comment by dulitz** [comment]
Good idea to crowdsource advice on anything auth related.

If there is one error code that correlates with the transient error, but ordinary auth failure is a different code, then I agree that the transient error should be a RetryableTotalConnectError.

If the two aren't cleanly distinguished, then it's more complicated but in this instance I'd still agree that we can retry it internally. Generally speaking one should not retry auth in the client if the server has indicated an auth failure, but since the server does wonky things I'm okay with it.

**Comment by austinmroczek** [comment]
It seems we didn't fix this one.  See https://github.com/home-assistant/core/issues/66537#issuecomment-1060056298

**Comment by dulitz** [comment]
I took a look at the HA issue. Looks to me like the error message he's reporting isn't to do with auth? So what happens is
 - there's internet flakiness which causes the TCP connection to time out
 - HTTPSConnection fails to establish a new connection, most likely because the internet is still down
 - ???

I'm not seeing the AuthenticationError. I understand that when one reauthenticates the problem goes away, but nothing in the linked HA issue (or this one for that matter) shows that an AuthenticationError is raised. (If you say it is I'm sure it is, but I don't see it here.)

If it isn't related to a particular transient error code, is it possibly the case that the server is requiring reauthentication whenever the connection closes?

I'm curious what is actually happening. Is it just that the server fails consistently for a while, and then by the time the user gets around to re-entering the credentials lots of time has passed and the server is fine again?

Or when HTTPSConnection gets into this state is there some problem with zeep that eventually causes an AuthenticationError because we're not properly recovering?

I'm looking at the block of code that remembers that auth failed with the previous password and doesn't retry auth until a new password is set. Clearly that is incompatible with server behavior that indicates invalid credentials sometimes but then works later with the same credentials. That block should be removed so that authenticate() always tries to authenticate.

**Comment by austinmroczek** [comment]
[Raising `ConfigEntryAuthFailed`](https://github.com/home-assistant/core/blob/a91888a7f81e1bf467395891764eab25913a98d3/homeassistant/components/totalconnect/__init__.py#L85
) triggers the prompt to user to re-authenticate in the HA user interface per https://developers.home-assistant.io/docs/integration_fetching_data.  That is only triggered following an `AuthenticationError` from our code.

I'm thinking about `USER_CODE_UNAVAILABLE` which also triggers AuthenticationError in our code.

**Comment by austinmroczek** [comment]
Also looking at https://github.com/craigjmidwinter/total-connect-client/issues/36

**Comment by dulitz** [comment]
So what you're saying is that the HTTPSConnection error is irrelevant -- or rather, it probably explains why we're reauthenticating. Okay.

Your observation is very interesting. Yet another reason not to cache an auth failure.

Maybe change the message argument to ConfigEntryAuthFailed so it includes the message from AuthenticationError? You're doing it the "right" way (`raise CEAF from exception`) but if HA doesn't log the `from` exception then you should also stash some information from it in the CEAF message so users can include it in the bug report.

**Comment by austinmroczek** [comment]
I'm planning to do a couple of things:

a) Make a new UsercodeUnavailable exception and split that out from AuthenticationError.  It's just a couple of extra lines and will help us prove/disprove that is the problem.

b) Will improve error messages in HA per your suggestion above, which should also provide us some better info for debugging.

**Comment by austinmroczek** [comment]
ok, think we've fixed it again.  updates for HA are next.
