### ISSUE TITLE
Add bypass_all_and_arm function

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#200]
See comments near https://github.com/craigjmidwinter/total-connect-client/issues/38#issuecomment-1258888618

**Comment by dulitz** [comment]
As I said in #38 I'm not in favor of this, because it leads to bad UI that can end up bypassing zones that the user doesn't know they bypassed. (Basically a UI race condition.) What I suggested in #38 was:

* Provide a control in HA that arms the system while bypassing whatever zones are currently being shown as faulted in the UI. This requires no API change.
* Make sure we always show in the HA UI which zones are faulted, whether or not they are bypassed.

If the HA API doesn't let you see what zones are faulted, that needs to be fixed before you add a "bypass all faulted zones" button.

If it does let you see what zones are faulted, then the zones displayed as faulted are precisely the zones that the "bypass all faulted zones" button should bypass. If another zone faults between the time those zones were updated and the time the "bypass all" button was pressed, then the arm should fail, the zone display can be updated, and the user can decide whether or not to push the "bypass all" button again.

**Comment by austinmroczek** [comment]
The problem with the HA UI is that the "alarm panel" widget is not nearly as full featured as the physical panel we have in our house.  It basically has Arm and Disarm buttons and shows status as Armed/Disarmed.  It does not list zones that are faulted, tampered, etc. 

HA does provide a binary sensor UI widget for each zone.  The sensor will be True/On for each faulted zone.  However these widgets are placed however the user decides, and are not part of the alarm panel widget.  

https://github.com/home-assistant/core/pull/73152 will help show users what is bypassed, though on a single zone basis.  It will create "diagnostic sensors" for each zone, including a binary sensor that is True/On if a zone is bypassed.

**Comment by austinmroczek** [comment]
As I understand the BypassAll TCC call at https://rs.alarmnet.com/TC21api/tc2.asmx?op=BypassAll it seems we would need to pass in a list of zones to bypass.  So if at time=0 we see zones 1, 2 and 3 faulted and request to bypass them, and at time=1 zone 4 faults while our request is still being processed, the alarm still would not arm, which is your point above.

**Comment by dulitz** [comment]
I think it would be a really excellent feature for the HA UI to include a text field in the alarm panel widget that can show zone status.

I know nothing about HA UI, but if keeping the existing minimal size of the alarm panel widget is important, a second widget (the "alarm zone" widget) could have zone-specific sensors for every zone as well as as "Arm Bypass" button that bypasses the zones that show faulted.

I agree with what you said about BypassAll, but now I'm not sure why one would do that instead of calling the existing zone_bypass() method? It potentially makes it faster if you're bypassing a lot of zones, but I think it's rare that someone bypasses more than 1 or 2 zones.

At this point I'm trying to understand why, and I guess I don't yet. Maybe I don't have to. :)

**Comment by austinmroczek** [comment]
We could probably find a way to use [Templating](https://www.home-assistant.io/docs/configuration/templating/) to make an Input Text entity that shows what zones are currently faulted.  This would be no new code in total_connect_client, but probably a pain figuring out the template.

Another option would be to raise a HomeAssistant exception in our code.  That will cause the UI to temporarily display a message for us.

**Comment by dulitz** [comment]
Raising an exception is fine for showing transient information. I think what we need to accomplish is that, when the user presses an "Arm Bypass" button, they already know what they're bypassing.

What happens today when a user presses "Arm" and the arm fails because a zone is faulted? Does it raise an exception saying what zones are faulted? Is the exception obvious to the user? If so, I guess HA could have an "Arm Bypass" button that bypasses all the zones that were reported in an exception raised within the last, say, 30 seconds.

**Comment by austinmroczek** [comment]
If a user presses Arm and a zone is faulted, a HomeAssistant exception is raised and the UI temporarily shows a message (~ 5 seconds).  There's also a log message.  I don't always see the pop up.

I shy away from the UI changes because it's not in my use case. I never use the HA "alarm panel" widget to control my alarm.  Everything is done via HA `automation` which is basically a script.  I have one automation that if the kitchen door code (smart lock also integrated with HA) is entered, then it does Disarm. I have another automation I trigger manually by hitting the "bedtime" button which turns off all the lights and does Arm Home.  All other manual arming is done via the actual panel next to the door, which is faster/easier.  Also, arming via panel allows me to set "silent exit" or whatever it is called so the panel doesn't beep for 30 seconds.  In the rare case where I try to Arm and a zone is bypassed (usually forgot the screen door in the summer time) the panel announces the problem "disarmed, not ready to arm" and I go investigate.

But I'm only one user.  If a good chunk of our users really use the UI, we could look at finding a way to show bypass status.

**Comment by mclever** [comment]
This functionality would be nice for summertime keeping the windows open at night but still being able to arm home and bypass open automatically

**Comment by austinmroczek** [comment]
@mclever @thor0215 and anyone else I'm looking for folks to test this new function "live" with their system.  To do so:

I'm assuming you already have Python installed and are at a command line (Windows/Linux/Mac should all work)

1. Download the code `git clone https://github.com/craigjmidwinter/total-connect-client.git` 
2. Change directory into the code `cd total_connect_client`
3. Run the main info script to find your location_id, a 6 digit number.  `python -m total_connect_client [your_username]`
4. Open a door or window or two that you want to bypass
5. Now run the bypass_all script `python -m total_connect_client.bypass_all [your_username] 123456=7890` where 123456 is your location_id from step 3 above, and 7890 is the PIN for your user. 
6. Report back results here.

**Comment by thor0215** [comment]
Here are my results.  Location ID has been removed and screenshot of bypassed zones is attached.

Attempt to bypass all zones.
Bypassing all for location XXXXXX
All zones bypassed.  Please verify zones are bypassed as expected.
Bypass will be cleared in 2 minutes.
Bypass will be cleared in 1 minute.
Clearing bypasses.
Clearing bypassing all for location XXXXXX
Cleared zone bypasses.  Please verify zones are faulted/open as expected.

![Screenshot_20230625_164025](https://github.com/craigjmidwinter/total-connect-client/assets/50240409/2b495d84-cc66-4fa0-9ddf-2c49d5c70795)

**Comment by austinmroczek** [comment]
Thanks.  What kind of hardware do you have?

**Comment by thor0215** [comment]
Honeywell L5100

**Comment by austinmroczek** [comment]
Hopefully coming soon in HA will be https://github.com/home-assistant/core/pull/114530 that adds a button for Bypass All.  It's not quite bypass_all_and_arm...but in HA a user could create an automation that pushes the bypass all button followed by arming the system.

**Comment by austinmroczek** [comment]
The pull request mentioned above made it into the `dev` branch in HA.  That means it should be included in the next release.
