### ISSUE TITLE
Find ArmMode for ArmCustom

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#201]
Per the API at https://rs.alarmnet.com/TC21api/tc2.asmx?op=CustomArmSecuritySystem and discussion at #38 

We need to find the "ArmMode" codes that work.  There is no documentation, so this will be trial and error.

If you have an alarm system that seems to support ArmCustom and are willing to help out please let me know.

**Comment by dulitz** [comment]
My suggestion from #38 was to remove the custom_arm and arm_custom methods from the API because we don't know of anything that ArmCustom does that can't be done another way.

Why would we go to the effort of trial and error without adding actual functionality?

We don't, afaict, need any additional API functionality to create a beautiful functional zone-by-zone bypassing experience in HA. Which of course should exist. :)

If we do need additional functionality in the API let's document exactly what we need, here.

**Comment by austinmroczek** [comment]
ArmCustom also has a parameter for "ArmDelay" which an integer.  I assume it's a number of seconds to delay arming of the system.  That parameter is not in any of the other TCC calls for arming.  I could see that being useful, even without any bypass stuff happening.
