### ISSUE TITLE
PartialResponseError on startup

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#205]
See https://github.com/home-assistant/core/issues/91703

User can see status in TC app and website, but cannot load data via Home Assistant.

Full log at original ticket above, but basic issue is here:
```txt
  File "/usr/local/lib/python3.10/site-packages/total_connect_client/location.py", line 258, in _update_zone_details
    raise PartialResponseError("no ZoneStatusInfoWithPartitionId", result)
total_connect_client.exceptions.PartialResponseError: ('no ZoneStatusInfoWithPartitionId', OrderedDict([('ResultCode', 0), ('ResultData', 'Success'), ('ZoneStatus', OrderedDict([('Zones', None)]))]))```
```

Maybe our refactoring of code has led to #112 coming back ?

In `location._update_zones()` if we see Zones=None we highlight that with a log message telling the user how to fix it, and then raise TotalConnectError.

But in `location._update_zone_details()` [which only runs once at startup] we don't provide a log message and raise PartialResponseError.

Waiting for the user to verify that a panel sync fixes this.

**Comment by GCSabas** [comment]
Quick follow-up: panel sync did not fix the issue.

**Comment by dulitz** [comment]
Yeah this is interesting. `GetZonesListInStateEx_V1` is the SOAP method that in the past has returned no zones when the panel wasn't synced. The method returning no zones now is `GetPanelMetaDataAndFullStatusEx_V2` and in the past that has returned zones always. @austinmroczek I say that because the earlier error was a repeatable failure in `GetZonesListInStateEx_V1` and it looks like in order to get there you already have to have successfully parsed the result of `GetPanelMetaDataAndFullStatusEx_V2`.

It's possible I'm misremembering the code history, I didn't pull the code from 2021 to check.

This looks much like the situation PartialResponseError is supposed to be raised for, but that doesn't help. @GCSabas can you see your zones in the TotalConnect webapp? If not, can you scroll through them on your keypad itself? Trying to see where TC lost the plot.

**Comment by austinmroczek** [comment]
This does not solve the current issue, but should we allow a panel to move forward with no zones (just give a warning)?  In theory you could just use a panel and the panel can alarm/trigger without a zone (I think).

**Comment by austinmroczek** [comment]
@GCSabas 

Is this your first time trying to use TotalConnect in HA, or was it previously working and now fails?

Please tell us your panel hardware (Lynx 7100, ProA7, etc).

Also, please run the [troubleshooting](https://github.com/craigjmidwinter/total-connect-client#troubleshooting) and give the results.  You've already been careful about removing personal data...but just a reminder.  You can run this from any computer with python, it doesn't have to be your HA device.  

Running troubleshooting It will generate a log file. We don't need the whole file (lots of extra junk happens at startup) but the any lines containing `GetZonesListInStateEx_V1` or `GetZonesListInStateEx_V1Response` please post.

**Comment by GCSabas** [comment]
You know, I wish I had SOME detail on this, but... damn thing started working.

To be clear, this was a NEW integration, so I did not have the option to dump the troubleshooting.  Maybe that's something that could be added to the integration setup?  Not clear how that works or if it's even possible.

I got on to attempt to troubleshoot, was hitting the same error, then kicked off another round of panel/user syncs.  To be clear, this is maybe the 12th or higher time I've done these at this point.

What I did next is the ONLY bit that I can think was different.

Usually, I wait a few minutes to see the "Sync completed" notification.  But I wasn't paying attention and jumped the gun.
While the panel sync had begun, I tried the user and pass and got... nothing.  No error.  No success.  An empty response that cleared the contents (user/pass inputs) of the setup window.

Closed the window.  Retried.  SAME.  Over and over.  Ran browser cache clears and full clears.  Finally, just decided to reboot HA system completely (HA Yellow).

The sync had completed long since, now.  Sign in again... asked me for the code!  Gave it the panel code and it worked!


I have no idea what might have happened.  The syncs had been done again and again.  Regardless, the same errors appeared on older users, too.
Maybe there was something... "stuck" on the API or panel side of things?

Not 100% sure where to find the the exact panel details - cannot find the docs.
The Vista 128P, Vista 15P, and Vista 20P all look about the same to me.  I'll see what I can locate.


I'm sorry there's not... MORE here.  Is there anything I can still do to try to help ID the issue?  Or might this come down to "Total Connect just being Total Connect?"

**Comment by austinmroczek** [comment]
Unfortunately the standard HA "download diagnostics" function only works once an integration is properly set up.  Outside of HA you can run the [troubleshooting](https://github.com/craigjmidwinter/total-connect-client#troubleshooting) but that is not as easy.

While your issue is fixed, would you mind dropping the HA diagnostics here.  If this happens again we can look for a pattern with hardware, settings, etc.

It may not solve it if this re-appears, but we can adjust the total_connect_client to give a more useful log message.

Thanks again for filing an issue.  That's pretty much the only way we get better.
